export const PLACE_TYPES = [
    // "acai_shop",
    // "african_restaurant",
    "american_restaurant",
    // "amphitheatre",
    // "amusement_park",
    "aquarium",
    "art_gallery",
    // "asian_restaurant",
    // "athletic_field",
    // "auditorium",
    // "bagel_shop",
    // "bakery",
    // "banquet_hall",
    // "bar",
    "bar_and_grill",
    // "barbecue_area",
    // "barbecue_restaurant",
    // "beach",
    // "bed_and_breakfast",
    // "book_store",
    // "botanical_garden",
    "bowling_alley",
    // "breakfast_restaurant",
    "brunch_restaurant",
    // "buffet_restaurant",
    "cafe",
    // "campground",
    "candy_store",
    // "casino",
    // "cat_cafe",
    // "chinese_restaurant",
    // "chocolate_shop",
    // "clothing_store",
    // "coffee_shop",
    // "comedy_club",
    // "community_center",
    "concert_hall",
    // "convention_center",
    // "cultural_center",
    // "cultural_landmark",
    "dance_hall",
    "deli",
    // "dessert_restaurant",
    // "diner",
    "dog_park",
    // "donut_shop",
    // "event_venue",
    // "farm",
    // "fast_food_restaurant",
    // "ferris_wheel",
    // "fine_dining_restaurant",
    // "fitness_center",
    "food_court",
    // "food_store",
    "garden",
    // "gift_shop",
    // "golf_course",
    // "grocery_store",
    "gym",
    // "hamburger_restaurant",
    // "hiking_area",
    // "historical_landmark",
    // "historical_place",
    // "hotel",
    "ice_cream_shop",
    // "ice_skating_rink",
    // "indian_restaurant",
    // "inn",
    // "internet_cafe",
    // "italian_restaurant",
    // "japanese_restaurant",
    // "jewelry_store",
    // "juice_shop",
    "karaoke",
    // "korean_restaurant",
    // "library",
    // "lodging",
    "market",
    // "massage",
    // "mediterranean_restaurant",
    // "mexican_restaurant",
    // "middle_eastern_restaurant",
    "monument",
    // "motel",
    "movie_theater",
    "museum",
    "national_park",
    "night_club",
    // "observation_deck",
    // "opera_house",
    "park",
    "performing_arts_theater",
    // "pet_store",
    // "picnic_ground",
    // "pizza_restaurant",
    // "planetarium",
    // "playground",
    "plaza",
    // "pub",
    // "public_bathroom",
    // "ramen_restaurant",
    // "resort_hotel",
    "restaurant",
    // "roller_coaster",
    // "sandwich_shop",
    // "sauna",
    // "sculpture",
    // "seafood_restaurant",
    "shopping_mall",
    // "skateboard_park",
    // "ski_resort",
    // "skin_care_clinic",
    // "spa",
    // "spanish_restaurant",
    "stadium",
    "steak_house",
    // "sushi_restaurant",
    // "swimming_pool",
    // "tanning_studio",
    // "tea_house",
    // "tour_agency",
    // "tourist_attraction",
    // "university",
    // "vegan_restaurant",
    // "vegetarian_restaurant",
    // "video_arcade",
    // "water_park",
    // "wellness_center",
    // "wildlife_park",
    "wine_bar",
    "yoga_studio",
    // "zoo"
  ];